name: Format Python Code

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install black

      - name: Check for unformatted code
        id: check-formatting
        run: |
          black --check .

      - name: Notify if unformatted
        if: steps.check-formatting.outcome == 'failure'
        run: echo "Unformatted code detected. Please run 'black .' to format."
